Vue3 migrate  (#214)
* cleanup

* cleanup

* single select filter module

* improved abstraction of filters

* cleanup

* cleanup

* better appearance of items select box and add multiple select option

* single select filter module

* improved abstraction of filters

* cleanup

* cleanup

* some more abstraction and cleanup

* refactor of query store. BREAKING: queryParam 'last_seen' now is called 'last-seen'

* wip

* added functionality for multiple select

* BREAKING: change url queries to slugs rather than values

* added type as a proper filterdefinition

* fixed bug that suddenly started throwing errors, inexplicably only for document list

* cleanup

* type based extension filter works

* complete re-refactor

* all code of re-refactor working properly and cleaned up

* fixed bug, added test

* fixed the 'any filetype' bug, fixed the tests

* fix minor bug

* remove file extensions filter for now

* add language filter and fix setting of filter values of route params in proper mutation

* fix code climate

* Work In progress, refactoring fully the filters

* unit tests passing

* remove some bugs with tests

* simplified definitions (fallback for slug to use label)

* fix bug with api query

* got the first component test working

* fixed several bugs using tdd and some code improvements

* turning classes into generator functions

* wip improving test suite and fixing tests

* wip; solving code errors

* wip

* clean up filter generator code

* clean up and get it to work, wip

* typefilter is working, fixed bug and test

* all unit tests working

* label change

* added "Other" type to options

* work in progress debugging the api calls

* Revert "added "Other" type to options"

This reverts commit 4268b1e9dfd3d294c8e1bd82b7581001e62f8b3a.

* got the different types to work again

* got the different types to work again

* got the different types to work again

* cleanup

* fixed bug of sending language filter to every file type api call

* refactored searchResults module

* rake in metadata through metadata-api for every hit

* codeclimate

* fixed a bug, and added/updated some docstrings

* remove some unnecessary whitelines in .eslintrc

* removed obsolete error catch, which was resolved by https://github.com/ipfs-search/ipfs-search-api/issues/25

* fixed nsfw lookup

* rename module generators for clarity

* fixed the appearance of the typefilter - again

* fix unit tests

* fix line length

* added "Other" type to options

* fix minor bug

* display the extra data

* prettier output for the metadata

* fix indents

* display the extra data

* added "Other" type to options

* list header "Other files" in stead of "files"

* Other

* more explicit the origin of the metadata

* fix eslint indentation

* fix the wrongly fixed merge conflict

* fixed the merge finally properly

* remove obsolete method

* extra metadata in nested dropdown

* fix eslint

* fix eslint

* display the extra data

* prettier output for the metadata

* fix indents

* more explicit the origin of the metadata

* fix eslint indentation

* remove obsolete method

* extra metadata in nested dropdown

* fix eslint

* fix eslint

* update dependencies for migrating to Vite

* Vite migration: move index.html and add vite.config.js (from previous branch)

* add .vue extension to auto-resolve extensions in vite.config.json

* remove webpack lazy loading hints and remove webpack speed measurement

* updated eslint to support es13, and fixed some dependencies

* update npm scripts

* fixed syntax error: cannot use import outside a module. Introduced Typescript and fixed jest-extended plugin support

* set testEnvironment to jsdom for jest

* added airbnb package to eslint; added jsconfig.json file to help IDE resolve @ paths

* removed type:module from package.json and ran `npm run lint:fix`

* all tests working

* cleanup, rename files

* fix vuetify components recognition

* fix env variables for Vite

* fix static assets references

* delete jest.config, add vitest.config to use vuetify

* fix another occurence of "require"

* components.d.ts

* fixed scss `~` shortcuts

* fix video css import

* fix favicon links

* fixed the unit tester

* updating components.d.ts for vuetify

* trying to fix codeclimate

* resolve eslint errors and add all .vue extensions

* ran install

* fix eslint script

* fixed eslint errors

* codeclimate different eslint version, see if this works

* spec ecmaversion 13

* spec ecmaversion 11

* some more small fixes

* shake up dependencies for upgrading to vue3

* stranger things happening

* going bumpy

* remove faulty line from vite.config.js

* eslint typescript fix and some build errors

* run eslint --fix

* trying to fix eslint settings

* fixing eslint settings, again

* fix alias __dirname replacement

* cleanup old vuetify artefacts

* fix vuex

* add vuetify to main.js

* fix main.js

* remove vuecomposition file

* replace Vue.set() with vue3 code

* bump vue router code

* upgrade timeago

* fix pretyBytes filter

* remove productionTip config

* vuetify vite plugin

* fix breakpoint api changes for vuetify

* fix "TypeError: url.parse is not a function"

* vuetify: replace v-subheader by v-list-subheader

* fix the prettybytes again

* correct timeago plugin. Fix some rebasing errors

* fix a bunch of vuetify things

* fix import

* fix selectedIndex coerce default to number 0 when undefined

* import vuetify styles

* fixed document viewer

* fix fetch function to work as reactive proxy objext

* fix document viewer colors

* fixed mediaheader

* move component files

* made rounded corners and the magnifier reappear

* aligned the searchbar parts

* aligned the searchbar parts better, colors of placeholder and caret fixed, and fixed search part of homepage

* fixed color theme. Fixed homeview. Improved homeview card code reuse

* fix top links

* fixing settings menu for vuetify3

* fix settings menu layout

* refactor all detail pages for usage with composition api

* fixing document list card

* refactored filelistmixin into composable

* Fixes #204 : no more metadata requests for directories

* fixed videolist and made generic headers

* fixed audiolist

* added picsum to the audio and video list for fun. With funky effects

* refactoring imagelist

* fix image detail view

* organize directories, fixes #173. And fix router props page number

* fixed imagedetail and carousel

* fixing routing; adds hrefs to the list views

* fixing routing; adds hrefs to the list views

* fix select filters

* refactored navigation bar to use setup script

* fix some bugs

* fixed routing/search

* put spinner on image detail page

* refactored detail pages

* fix and refactor audio player

* refactor audioplayer to use composition api in setup script

* bump vuetify to v3beta5

* fixing the footer

* fixed directory detail page and add iframe loader

* make logo routerlinks

* fix metadata time issue

* moved iframe styling to style section

* generic header component and various small style fixes

* added hyperlink component

* fix layout audiolist and fix slicing on any-type page

* fix background color for dropdown menus. For now (until darkmode is fixed)

* fix list headers

* fix videolist margins

* fixed style hack for searchbar

* removed non-existent tags

* fix image list

* remove merge artifact

* replaced material design icons with treeshakeable svg version; reduced build size by 2.8mb (!)

* some renaming

* fix types menu style

* fix directory references

* patch up detail header

* fix button caption to top

* fixed audio detail page and refactored the audioPlayer

* audio player mostly functional, except for close function. And styling

* fixed styling for audio player

* add marquee effect to audio player

* move file

* fix search page

* fix audio controls and error messaging

* got the unit tests to work

* added prettier

* Fix README.md. Pre-commit hooks option for prettier

* setup codeclimate

* refactor/fix code to suit eslint needs

* dealt with duplication issue of codeclimate

* fixed production-build related errors

* change ecmascript version to "allowed" value

* downgrade eslint for codeclimate

* downgrade eslint even further to try to fix codeclimate

* refactoring fetchDoggy for codeclimate improvement and filelist composable

* try different settings in eslintrc

* try different settings in eslintrc

* refactored the code to reduce codeclimate complexity; no more codeclimate issues

* fix html title

* fix changing placeholders for audio and video

* refactor picsum for readability

* hide dark mode switch

* fixed and improved the marquee component

* fix codeclimate

* test and fix picsum module

* converted picsum to TS and fixed TS support

* refactored marquee into typescript